# strict check mode
# if issues, exit with fail
run:
  issues-exit-code: 1
  # timeout for analysis, default is 1m.
  # NOTE(Jess): I've hit the 1m timeout like once so its not a big deal I just want to give us a little buffer
  timeout: 5m

  # list of build tags, all linters use it.
  build-tags:
    - integration
# output configuration options
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - typecheck
    - varcheck
  disable:
    - gosimple
    - staticcheck
    - structcheck
    - unused

# WARN [linters context] gosimple is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
# WARN [linters context] staticcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
# WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
# WARN [linters context] unused is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.

linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true

    govet:
    # report about shadowed variables
    check-shadowing: true # we had this enabled on the old check script. I was under the impression it was already enabled here
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
